version: '3'

services:
  db:
    image: postgres
    volumes:
    - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8001:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=sanghee911@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=root123
  web:
    build:
      context: ./todo-list-django
    volumes:
      - django-data:/src
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build:
      context: ./todo-list-nginx
    ports:
      - "8888:8888"
    volumes:
      - django-data:/src
    depends_on:
      - web

  frontend:
    build:
      context: ./todo-list-frontend
    ports:
      - "8080:8080"
    depends_on:
      - nginx

volumes:
  django-data:
  postgres-data:
