apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-data-pv
          ports:
            - containerPort: 5432
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "sanghee911@hotmail.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "root123"
      volumes:
        - name: postgres-data-pv
          persistentVolumeClaim:
           claimName: postgres-data-pv-claim
